### ISSUE TITLE
Mobile UI and BlackBerry 10

### ISSUE THREAD

**Issue by BGmot** [wolfpet/kitchen#53] opened 2015-08-28 13:41 UTC
On my BlackBerry I can see only top level - Threads, when I tap on any it'll go into "Message (L:1)" with empty screen (only top and bottom bars).

**Comment by wolfpet** [comment] 2015-08-28 15:39
Is it one of the new BB10 series or some classic BB?

**Comment by BGmot** [comment] 2015-08-28 17:51
BB10.

**Comment by wolfpet** [comment] 2015-08-28 19:19
That's interesting.  BB Z30 emulator renders everything properly.   Also a friend of mine tried to load the UI with his BB Z10 -- all worked just fine. Can you try to login, then open the context menu and check if the issue persists for "Answered" and "Recent" views?

**Comment by EvgenyY** [comment] 2015-08-28 23:55
I don't have anything in answered but Recent has the same issue. It seems like the message appears for milliseconds and then blank screen.
![img_20150828_195339](https://cloud.githubusercontent.com/assets/801429/9559270/a3e9d0a4-4dbe-11e5-96fd-7bbd0730f3f3.png)

**Comment by wolfpet** [comment] 2015-08-29 04:56
Sorry, I know very little about BB platform. Is there any choice of web browsers? What's the default browser?

**Comment by wolfpet** [comment] 2015-08-29 05:04
The thing is that If you look at the code you'll realize that with modern frameworks such as JQuery or Intel AF there's very little control over the actual rendering. The HTML is super-simple but the way CSS is applied is 99% framework and 1% the developer ;-).  The current code has been tested against a few versions of Android, iOS and WP8 natively as well as a few more phone models in emulators. All seem to render the page fine. So, the only way to isolate the issue is through several steps of creating sample static pages, where each subsequent page getting more elements, closer to the current one. You will need to open every page and report if it renders properly.  If you feel there is a faster way please share. There is always an option to say "we don't support Blackberry OS" if we fail ;-)

**Comment by BGmot** [comment] 2015-08-29 16:20
I see... Thanks for trying to help.
Probably it's time for me to touch web development -) so far I have 'touched' only Assembler, C/C++, perl, php, ruby -)))
Please assign this ticket to me.

**Comment by wolfpet** [comment] 2015-08-30 03:11
I'm pretty sure we could get to the bottom of it. I'm happy to help on my free time.  Also, I double-checked today by asking someone to open the site on his Z10 again.  I saw it working fine. So, this could be specific for your device. I'm curious if you were able to reproduce on any other BB10 device.

P.S. Javascript is not very hard, as long as you understand the concept of the markup and styles. Next time I'm coding I could create a static sample and ask you to try it if this is OK. Of corse, feel free to try yourself! And one more thing. I understand you can put any Android app on BB. Can you try to load Chrome? I wonder if this will fail with it as well.

**Comment by BGmot** [comment] 2015-09-13 21:43
Everything works ok if I comment line 408 in app.js:

```
    /// Scroll up
    document.getElementById("msgBody").parentElement.removeAttribute("style");
```

Tested on BB Z10, Q10 and Passport. Any chance you can 'fix' this?
Thanks.

**Comment by wolfpet** [comment] 2015-09-13 22:37
This is one very strange glitch. OK, I put a temp fix for now.
This is a somewhat desperate attempt to scroll up every time one loads the message. It works fine in all emulators but I noticed that some android browser versions simply ignore it.  Works like a charm on WP8 though but breaks BB10. Go figure.  Well, try now. Should be OK. And thanks for the report!

**Comment by iamranger** [comment] 2015-09-14 00:01
Promoted to prod.

**Comment by BGmot** [comment] 2015-09-14 00:06
You are quick guys -)
Works on BB, thanks!

**Comment by iamranger** [comment] 2015-09-14 02:25
Others promise, we deliver :) You're welcome!

**Comment by wolfpet** [comment] 2015-09-14 16:26
Gotta close this one

**Closed as completed by wolfpet** 2015-09-14 16:26 UTC
